### ISSUE TITLE
Undefined behaviour in vorbis_rs

### ISSUE THREAD

**Issue by jasonyu1996** [ComunidadAylas/vorbis-rs#22]
Hi! In vorbis_rs, the encoder state is created with `vorbis_info`, `vorbis_dsp_state`, and `vorbis_block` all owned by the `VorbisEncodingState` object, but with pointers pointing to one another.

https://github.com/ComunidadAylas/vorbis-rs/blob/c01a3eafe4e9dfa92443483b42313bd35c3a4b21/packages/vorbis_rs/src/encoder/encoder_util.rs#L20-L50

https://github.com/ComunidadAylas/vorbis-aotuv-lancer/blob/1c49413115971752e360025af58f0e418106e7b9/lib/block.c#L84-L107

Then mutation is performed using such pointers rather than through those owner references or references/pointers derived from them:

https://github.com/ComunidadAylas/vorbis-aotuv-lancer/blob/1c49413115971752e360025af58f0e418106e7b9/lib/analysis.c#L40

This is an undefined behaviour and may cause miscompilation. A simplified demo https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=a98129c85a837c05db5958f33c24fe18 shows different results under debug and release. MIRI can catch this issue in the simplified demo but unfortunately does not work for the original code because it does not support FFI.

**Comment by AlexTMjugador** [comment]
Hello, thank you so much for reporting this issue!

I was not aware of the consequences of pointer aliasing in the context of Box ownership semantics, so your report is incredibly valuable: this is something I'd have likely overlooked otherwise. While researching the topic further, I found a several useful resources: the ["Behavior considered undefined" page](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in the Rust reference, a really interesting [blog post titled "Box Is a Unique Type"](https://noratrieb.dev/blog/posts/box-is-a-unique-type/), and a [recent addition to the documentation for the `std::boxed` module](https://doc.rust-lang.org/nightly/std/boxed/index.html#considerations-for-unsafe-code). These resources led me to a helpful comment by @RalfJung:

> > I guess to be on the safe side I should use more unsafe and get away from Box as early as possible, so all the raw pointers are derived from the result of Box::into_raw, and not from when the box is live (even though they have the same address they have different provenance?).
> 
> Indeed, that is the correct approach. Mixing `Box` and raw ptr accesses to the same location is running a high risk of violating aliasing guarantees.

Therefore, I addressed the undefined behavior in question in [this commit](https://github.com/ComunidadAylas/vorbis-rs/commit/02c3674cd6268dd9d66a95c32c7315758c2fd885) by modifying the code to bail out of `Box`'s non-aliasing semantics as soon as possible. To avoid leaking memory with the resulting raw pointers, I manually reconstruct the `Box` only when it's time to free them, after calling the corresponding teardown C functions. The primary reason I had kept the `Box` around was to leverage its automatic memory cleanup on drop.

To validate this approach, [I adapted your reduced playground example using the same fix](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=3a0174f2bdaaf193e6b517b0c90f9511) and successfully tested it with Miri.

I'd greatly appreciate it if you could review the changes in the referenced commit to confirm whether the fix looks good to you as well, just to make sure I haven't missed any other thing :innocent:

**Comment by jasonyu1996** [comment]
> Hello, thank you so much for reporting this issue!
> 
> 
> 
> I was not aware of the consequences of pointer aliasing in the context of `Box` ownership semantics, so your report is incredibly valuable: this is something I'd have likely overlooked otherwise. While researching the topic further, I found several useful resources for me and potentially other people under similar circumstances: the ["Behavior considered undefined" page](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in the Rust reference, a really interesting [blog post titled "Box Is a Unique Type"](https://noratrieb.dev/blog/posts/box-is-a-unique-type/), and a [recent addition to the documentation for the `std::boxed` module](https://doc.rust-lang.org/nightly/std/boxed/index.html#considerations-for-unsafe-code). These resources led me to a helpful comment by @RalfJung:
> 
> 
> 
> > > I guess to be on the safe side I should use more unsafe and get away from Box as early as possible, so all the raw pointers are derived from the result of Box::into_raw, and not from when the box is live (even though they have the same address they have different provenance?).
> 
> > 
> 
> > Indeed, that is the correct approach. Mixing `Box` and raw ptr accesses to the same location is running a high risk of violating aliasing guarantees.
> 
> 
> 
> Therefore, I addressed the undefined behavior in question in [this commit](https://github.com/ComunidadAylas/vorbis-rs/commit/02c3674cd6268dd9d66a95c32c7315758c2fd885) by modifying the code to bail out of `Box`'s non-aliasing semantics as soon as possible. To avoid leaking memory with the resulting raw pointers, I manually reconstruct the `Box` only when it's time to free them, after calling the corresponding teardown C functions; the primary reason I had kept the `Box` around was to leverage its automatic memory cleanup on drop, after all.
> 
> 
> 
> To validate this approach, [I adapted your reduced playground example using the same fix](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=3a0174f2bdaaf193e6b517b0c90f9511) and successfully tested it with Miri.
> 
> 
> 
> I'd greatly appreciate if you could review the changes in the referenced commit to confirm whether the fix looks good to you as well, just to make sure I haven't missed any other thing :innocent: 

Thanks! I will check out the commits when I get the time.

**Comment by jasonyu1996** [comment]
Hi! @AlexTMjugador I've checked out the changes and they look good to me.

**Comment by AlexTMjugador** [comment]
Splendid, thanks a bunch for your review! Let's close this issue as resolved then 👍
